version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - PG_PASSWORD=postgres
    volumes:
      - ./:/opt

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports: 
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@site.org
      - PGADMIN_DEFAULT_PASSWORD=Q1w2e3r4
    volumes:
      - ~/.pgadmin_data:/var/lib/pgadmin/
